# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66e4ff3e6a3081d06aeb8614f85846eb9d9c533e290f237c49059cfd3cc444f493863f2d62eec8f5669707a845a11b50996b1b94ba55fb78d7831240782c0de8

test:
  secret_key_base: b8f0385344d73f19b86bca2938e1a883ddc40807cb5d4a2c1434ef632abcc96ec6b0962347899c69b431b6a1ad37d249baf55b07066da4842b783c6cdab78129

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
